version: "3.8"

services:
  golang-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go-gin-server
    ports:
      - "5000:8000"
    command: ./main
    restart: unless-stopped
